name: special_calendar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  provider: ^6.1.2
  sizer: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/icons/
